routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VehicleManagmentController;
use App\Http\Livewire\Admin\Vehicle\Manage\Booking\Show;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\VansController::class, 'index'])->name('welcome');
Route::get('/vehicle/{van}', [\App\Http\Controllers\VansController::class, 'show'])->name('vehicle');
Route::view('/rental-conditions', 'about-us')->name('rentalConditions');

Route::get('/register/{token}', [AuthController::class, 'registerForm'])->name('register');
Route::post('/register/store', [AuthController::class, 'sotreUser'])->name('userStore');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('users', UserController::class);
    Route::resource('vehicleManagment', VehicleManagmentController::class);
    Route::get('vehicleManagment/{van}/booking/{booking}', Show::class)->name('booking.show');
});

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/about-us.blade.php
<x-guest-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            @lang('Camping cottage rental conditions')
        </h2>
    </x-slot>
    <div id="about-us-content">
        <h3 class="font-bold text-lg text-gray-800 leading-tight mt-4">
            Üldtitingimused
        </h3>
        <p class="my-2">
            Matkaauto rentimiseks esitab rentnik kehtiva juhiloa ning isikut tõendava dokumendi (ID kaart või pass). Matkabussi rentimiseks peab rentnik olema vähemalt 21-aastane ning omama vähemalt 3-aastast B-kategooria juhistaaži. A-klassi täisintegreeritud mudelite (LUX-klass) puhul on nõutav juhistaaž vähemalt 5 aastat. Kui soovite sõidukit rentida ettevõtte nimele, siis peab lepingu allkirjastama juhatuse liige või selleks volitatud isik, esitades rendifirmale vastavasisulise ning sobiva volikirja koos volituse kehtivust tõendavate dokumentidega (volikiri, garantiikiri, äriregistri B-kaardi koopia). Samuti kuulub sellisel juhul lisaks rendilepingule allkirjastamisele käendusleping, millega sõiduki kasutaja tagab ettevõtte võetud kohustusi.
        </p>
        <p class="my-2">
            Rentnikule antakse üle tangitud, puhastatud ning tehniliselt korras matkaauto. Sõidukit vastu võttes soovitame Teil see hoolikalt üle vaadata ning fikseerida sõidukit vastu võttes avastatud vigastused ning puudujäägid (sh kriimustused, puuduv või katkine varustus jms), vastasel juhul võite jääda vastutavaks vigastuste/puuduste eest, mis olid sõidukil juba enne Teie kasutusse andmist. Rendileandja ei vastuta otseselt ega kaudselt kahjude eest, mis võivad Rentnikule tuleneda matkaauto tehnilisest rikkest ning kui seoses eelnevaga reis katkeb või viibib.
        </p>
        <p class="my-2">
            Matkaauto antakse rentnikule üldjuhul üle täidetud kütusepaagiga. Matkaauto tagastamisel mitte täis paagiga arvestatakse renditasule juurde tasu puuduoleva kütuse iga liitri eest vastavalt Circle K kehtivale hinnakirjale ning tasu tankimise eest 50 EUR (sisaldab käibemaksu). Rendileandjal on õigus antud summad kinni pidada tagatisrahast. Valesti tangitud kütusest tekitatud kahju korvab rentnik.
        </p>

        <h3 class="font-bold text-lg text-gray-800 leading-tight mt-4">
            Broneerimine, tagatisraha ning tasumine
        </h3>
        <p class="my-2">
            Matkaauto broneerimistasu on 30% rendiperioodi kogumaksumusest, minimaalselt 300 EUR. Broneerimise kinnitamiseks loetakse broneerimistasu laekumist eletri OÜ arveldusarvele ning see tuleb tasuda 3 päeva jooksul alates rendileandjalt kirjaliku kinnituse või vastavasisulise arve saamist broneeringu kinnituse kohta. Kõrghooajal broneerimisel (perioodil 01.06. kuni 31.08.), tehes broneeringu vähem kui 30 päeva enne rendiperioodi algust tasub rentnik broneerimisel broneerimistasu 50% rendihinnast.
        </p>
        <p class="my-2">
            Rentnikule kinnitatud broneeringutele võib teha muudatusi alates reserveeringu tegemise kuupäevast kuni vähemalt 90 päeva enne kokkulepitud rendiperioodi algust ning seda vaid juhul, kui rendileandjal on võimalik pakkuda alternatiivseid võimalusi ja alternatiivne broneering vastab kogusummalt esialgsele. Broneerimistasu ei tagastata, vaid see arvestatakse renditasu sisse. Broneeringu kliendipoolsel tühistamisel vastutab klient broneerimistasu ulatuses ning broneerimistasu ei tagastata.
        </p>
        <p class="my-2">
            Matkaauto rentnik maksab lepingu nõuete täitmise tagatisraha 500 EUR (LUX klassi täisintegreeritud mudelite puhul kuni 1000 EUR), mis lepingu lõpetamisel ning nõuete puudumise korral korral rentnikule tagastatakse.
        </p>
        <p class="my-2">
            Ülejäänud renditasu ning tagatisraha tasutakse enne rendiperioodi algust vastavalt rendilepingus kokkulepitud tähtaegadel. Lõplik arveldamine toimub pärast sõiduki tagastamist rendileandjale. Renditasu on võimalik tasuda nii pangaülekandega kui sularahas.
        </p>
        <p class="my-2">
            Rendihind sisaldab õlide, hoolduse, kohustusliku liikluskindlustuse ja täiskasko kindlustuse maksumust. Rendihind ei sisalda autokütuse maksumust.
        </p>

        <h3 class="font-bold text-lg text-gray-800 leading-tight mt-4">
            Kindlustused, vastutus kolmandate isikute ees
        </h3>
        <p class="my-2">
            Matkabusside rendi hinnad sisaldavad kaskokindlustust (avarii, vandalism) rentniku omavastutusega 500 EUR (LUX klassi täisintegreeritud mudeli puhul 1000 EUR) ja varguskindlustust rentniku omavastutusega 15% sõiduki maksumusest (sõiduki väärtus toodud rendilepingus). Sõidukite rehvid ja veljed ei ole kindlustatud ning nii rehvide kui ka velgede osas kannab rentnik täielikku materiaalset vastutust. Matkabussi ärandamise või varguse korral on rentnik kohustatud esitama auto võtmed ja sõiduki registreerimistunnistuse. Ärandamine või vargus peab olema rentniku poolt registreeritud varguse või ärandamise toimumiskoha järgses politseijaoskonnas. Liiklusõnnetuse korral on rentnik kohustatud teatama sellest kindlasti politseisse ja võtma kirjaliku tõendi õnnetuse toimumise kohta koos asjaolude selgitamisega kindlustuse jaoks. Kohe tuleb ühendust võtta ka rendifirmaga (kontaktandmed leiate rendilepingult).
        </p>
        <p class="my-2">
            Kõik rentniku ja/või matkasuvila kasutajate poolt rendiperioodi jooksul põhjustatud nõuded kolmandatelt isikutelt (näiteks liikluseeskirjade rikkumised, parkimistrahvid, viivistasu otsused, auto teisaldamised jms) kuuluvad rentniku ja/või auto kasutajate poolt täielikule hüvitamisele ka tagantjärgi.
        </p>

        <h3 class="font-bold text-lg text-gray-800 leading-tight mt-4">
            Sõiduki üleandmine ja tagastamine, rendiperiood
        </h3>
        <p class="my-2">
            Rendiperiood algab esimesel rendipäeval alates kell 14:00 ning lõppeb rendiperioodi lõpp-päeval hiljemalt kell 11:00, kui poolte vahel ei ole kokkulepitud teisiti. Kui matkaauto tagastatakse rohkem kui 1 tund hiljem eelnevalt kokkulepitud ajast, on Rendileandjal õigus rendisummale lisada täiendavalt ühe rendipäeva tasu. Kui Rentnik hilineb sõiduki tagastamisega rohkem kui ühe päeva, siis on Rendileandjal õigus nõuda hilinetud päevade eest topelt renti.
        </p>
        <p class="my-2">
            Matkaauto tagastatakse Rentniku poolt Rendileandjale siseruumid hoolikalt puhastatuna, reoveepaak ning WC-kassett tühjendatuna sarnaselt sellele, milline auto oli rendile võtmise hetkel. Juhul, kui sõiduk tagastatakse koristamata ning see ei ole eelnevalt Rentniku ja Rendileandja vahel kokku lepitud, on Rendileandjal õigus nõuda leppetrahvi. Ettetellimisel on matkaauto siseruumide koristuse hind 80 EUR. Reoveepaakide ning WC-kasseti tühjendamise ja puhastamise hind on 30 EUR. Autos ei tohi ilma eelneva kokkuleppeta vedada lemmikloomi. Matkaautos suitsetamine on rangelt keelatud. Nõude rikkumise korral on Rendileandjal õigus nõuda leppetrahvi 300 EUR (LUX klassi täisintegreeritud mudeli puhul 500 EUR). Ülalnimetatud summad on Rendileandjal õigus kinni pidada tagatisrahast.
        </p>
        <p class="my-2">
            Autoelamu tagastamisel kuulub välipesu sõiduki rendihinna sisse ning selle teostab Rendileandja omal kulul.
        </p>
        <p class="my-2">
            Sõiduki tagastamisel teostavad auto ülevaatuse Rendileandja ja Rentnik koos. Vead, mida ei olnud rendile andmise hetkel ja mida ei saa lugeda normaalseks kulumiseks korvab Rentnik autoesinduse hinnakirja alusel.
        </p>
        <p class="my-2">
            Autoelamu rendi minimaalne periood on kolm ööpäeva. Kõrghooajal (01.06. kuni 31.08. ja koolivaheaegadel) on minimaalne rendiperiood 7 päeva. Matkaautol läbisõidupiirangut ei ole.
        </p>
        <p class="my-2">
            Sõiduki rentnikule üleandmisel või rentnikupoolsel tagastamisel pühapäeviti või riiklikel pühadel lisandub renditasule 30 EUR.
        </p>

        <h3 class="font-bold text-lg text-gray-800 leading-tight mt-4">
            Varustus
        </h3>
        <p class="my-2">
            Talveperioodil on matkaautod varustatud talverehvidega. Kõik meie autoelamud on varustatud GPS-seadmetega, mis võimaldavad Rendileandjal jälgida sõiduki sihtotstarbelist kasutamist. Vastavalt poolte kokkuleppele annab Rendileandja Rentniku kasutusse lisavarustuse, millise täpne nimekiri on fikseeritud rendilepingus.
        </p>

        <h3 class="font-bold text-lg text-gray-800 leading-tight mt-4">
            Lepingu kehtivus
        </h3>
        <p class="my-2">
            Iga allakirjutatud leping on siduv – ka juhul, kui Rentnik ei ole seda läbi lugenud või sellest aru saanud. Soovitame alati enne lepingu allkirjastamist tingimused täpselt läbi lugeda ning vajadusel täpsustada. Hilisemaid pretensioone ei rahuldata või lahendatakse kohtus.
        </p>

        <h3 class="font-bold text-lg text-gray-800 leading-tight mt-4">
            Sõitmine Eestist väljapoole
        </h3>
        <p class="my-2">
            Klient ei tohi renditud matkaautoga sõita väljapoole Euroopa Liitu (v.a. Norra, Šveits, Lichtenstein, Andorra). Vastav soov kooskõlastada kirjalikult rendifirmaga enne rendiperioodi algust vähemalt 14 päeva.
        </p>

        <h3 class="font-black text-lg text-gray-800 leading-tight mt-4">
            Täpsemad tingimused on toodud Rendileandja ning Rentniku vahel sõlmitavas rendilepingus.
        </h3>
    </div>
</x-guest-layout>

resources/views/navigation-menu.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="flex items-center overflow-hidden shrink-0">
                    <a href="{{ route('welcome') }}">
                        <img src="{{ asset('assets/Rendimatkabuss_logod.jpg') }}" class="block w-auto" />
                    </a>
                </div>

                <!-- Navigation Links -->
                {{-- left side of navbar --}}
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    @can('manage vehicles')
                    <x-jet-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-jet-nav-link>
                    @endcan
                    @can('manage vehicles')
                        <x-jet-nav-link href="{{ route('vehicleManagment.index') }}" :active="request()->routeIs('vehicleManagment.index')">
                            {{ __('Vehicle managment') }}
                        </x-jet-nav-link>
                    @endcan
                    @can('edit users')
                        <x-jet-nav-link href="{{ route('users.index') }}" :active="request()->routeIs('users.index')">
                            {{ __('Users') }}
                        </x-jet-nav-link>
                    @endcan
                </div>
            </div>

            <div class="hidden sm:flex sm:items-center sm:ml-6">
                {{-- right side of navbar --}}
                <x-jet-nav-link href="{{ route('welcome') }}" :active="request()->routeIs('welcome')" class="font-bold">
                    {{ __('Vehicles') }}
                </x-jet-nav-link>
                <x-jet-nav-link href="{{ route('rentalConditions') }}" :active="request()->routeIs('aboutUs')" class="font-bold">
                    {{ __('Rental conditions') }}
                </x-jet-nav-link>
                <!-- Teams Dropdown -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="relative ml-3">
                        <x-jet-dropdown align="right" width="60">
                            <x-slot name="trigger">
                                <span class="inline-flex rounded-md">
                                    <button type="button" class="inline-flex items-center px-3 py-2 text-sm font-medium leading-4 text-gray-500 transition bg-white border border-transparent rounded-md hover:bg-gray-50 hover:text-gray-700 focus:outline-none focus:bg-gray-50 active:bg-gray-50">
                                        {{ Auth::user()->currentTeam->name }}

                                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </span>
                            </x-slot>

                            <x-slot name="content">
                                <div class="w-60">
                                    <!-- Team Management -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Manage Team') }}
                                    </div>

                                    <!-- Team Settings -->
                                    <x-jet-dropdown-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">
                                        {{ __('Team Settings') }}
                                    </x-jet-dropdown-link>

                                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                                        <x-jet-dropdown-link href="{{ route('teams.create') }}">
                                            {{ __('Create New Team') }}
                                        </x-jet-dropdown-link>
                                    @endcan

                                    <div class="border-t border-gray-100"></div>

                                    <!-- Team Switcher -->
                                    <div class="block px-4 py-2 text-xs text-gray-400">
                                        {{ __('Switch Teams') }}
                                    </div>

                                    @foreach (Auth::user()->allTeams() as $team)
                                        <x-jet-switchable-team :team="$team" />
                                    @endforeach
                                </div>
                            </x-slot>
                        </x-jet-dropdown>
                    </div>
                @endif

                <!-- Settings Dropdown -->
                @if (Auth::user())
                <div class="relative ml-3">
                    <x-jet-dropdown align="right" width="48">
                        <x-slot name="trigger">
                            @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                                <button class="flex text-sm transition border-2 border-transparent rounded-full focus:outline-none focus:border-gray-300">
                                    <img class="object-cover w-8 h-8 rounded-full" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                                </button>
                            @else
                                <span class="inline-flex rounded-md">
                                    <button type="button" class="inline-flex items-center px-3 py-2 text-sm font-medium leading-4 text-gray-500 transition bg-white border border-transparent rounded-md hover:text-gray-700 focus:outline-none">
                                        {{ Auth::user()->name }}

                                        <svg class="ml-2 -mr-0.5 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                            <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                        </svg>
                                    </button>
                                </span>
                            @endif
                        </x-slot>

                        <x-slot name="content">
                            <!-- Account Management -->
                            <div class="block px-4 py-2 text-xs text-gray-400">
                                {{ __('Manage Account') }}
                            </div>

                            <x-jet-dropdown-link href="{{ route('profile.show') }}">
                                {{ __('Profile') }}
                            </x-jet-dropdown-link>

                            @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                                <x-jet-dropdown-link href="{{ route('api-tokens.index') }}">
                                    {{ __('API Tokens') }}
                                </x-jet-dropdown-link>
                            @endif

                            <div class="border-t border-gray-100"></div>

                            <!-- Authentication -->
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf

                                <x-jet-dropdown-link href="{{ route('logout') }}"
                                         onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                    {{ __('Log Out') }}
                                </x-jet-dropdown-link>
                            </form>
                        </x-slot>
                    </x-jet-dropdown>
                </div>
                @endif
            </div>

            <!-- Hamburger -->
            <div class="flex items-center -mr-2 sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 text-gray-400 transition rounded-md hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500">
                    <svg class="w-6 h-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-jet-responsive-nav-link href="{{ route('welcome') }}" :active="request()->routeIs('welcome')">
                {{ __('Vehicles') }}
            </x-jet-responsive-nav-link>
            <x-jet-responsive-nav-link href="{{ route('rentalConditions') }}" :active="request()->routeIs('rentalConditions')">
                {{ __('Rental conditions') }}
            </x-jet-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        @if(Auth::user())
            <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="flex items-center px-4">
                @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                    <div class="mr-3 shrink-0">
                        <img class="object-cover w-10 h-10 rounded-full" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                    </div>
                @endif

                <div>
                    <div class="text-base font-medium text-gray-800">{{ Auth::user()->name }}</div>
                    <div class="text-sm font-medium text-gray-500">{{ Auth::user()->email }}</div>
                </div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Account Management -->
                <x-jet-responsive-nav-link href="{{ route('profile.show') }}" :active="request()->routeIs('profile.show')">
                    {{ __('Profile') }}
                </x-jet-responsive-nav-link>

                @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                    <x-jet-responsive-nav-link href="{{ route('api-tokens.index') }}" :active="request()->routeIs('api-tokens.index')">
                        {{ __('API Tokens') }}
                    </x-jet-responsive-nav-link>
                @endif

                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-jet-responsive-nav-link href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                    this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-jet-responsive-nav-link>
                </form>

                <!-- Team Management -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <div class="border-t border-gray-200"></div>

                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Manage Team') }}
                    </div>

                    <!-- Team Settings -->
                    <x-jet-responsive-nav-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}" :active="request()->routeIs('teams.show')">
                        {{ __('Team Settings') }}
                    </x-jet-responsive-nav-link>

                    @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                        <x-jet-responsive-nav-link href="{{ route('teams.create') }}" :active="request()->routeIs('teams.create')">
                            {{ __('Create New Team') }}
                        </x-jet-responsive-nav-link>
                    @endcan

                    <div class="border-t border-gray-200"></div>

                    <!-- Team Switcher -->
                    <div class="block px-4 py-2 text-xs text-gray-400">
                        {{ __('Switch Teams') }}
                    </div>

                    @foreach (Auth::user()->allTeams() as $team)
                        <x-jet-switchable-team :team="$team" component="jet-responsive-nav-link" />
                    @endforeach
                @endif
            </div>
        </div>
        @endif
    </div>
</nav>

resources/views/vehicle.blade.php
<x-guest-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ $vehicle->name }} {{ $vehicle->model }}
        </h2>
    </x-slot>

    <x-carousel
        :images="$vehicle->images()->pluck('path')->toArray()"></x-carousel>
    <div class="my-2 lg:grid lg:grid-cols-2">
        <div class="grid grid-cols-2 my-2 md:my-4 py-2">
            @foreach($vehicle->attributes as $vanAttribute)
                <div class="grid grid-cols-2">
                    <span>{{ __($vanAttribute->attribute->label) }}: </span><span>{{ __($vanAttribute->value) }}</span>
                </div>
            @endforeach
        </div>
        <div class="flex flex-col md:flex-row md:transform md:scale-75 lg:scale-100 justify-center">
            <livewire:components.price-list :vehicle="$vehicle">
        </div>
    </div>

    <livewire:booking.form :vehicle="$vehicle"></livewire:booking.form>
</x-guest-layout>