routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VehicleManagmentController;
use App\Http\Livewire\Admin\Vehicle\Manage\Booking\Show;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\VansController::class, 'index'])->name('welcome');
Route::get('/vehicle/{van}', [\App\Http\Controllers\VansController::class, 'show'])->name('vehicle');
Route::view('/rental-conditions', 'about-us')->name('rentalConditions');

Route::get('/register/{token}', [AuthController::class, 'registerForm'])->name('register');
Route::post('/register/store', [AuthController::class, 'sotreUser'])->name('userStore');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::resource('users', UserController::class);
    Route::resource('vehicleManagment', VehicleManagmentController::class);
    Route::get('vehicleManagment/{van}/booking/{booking}', Show::class)->name('booking.show');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        return view('admin.users.index', ['users' => User::all()]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        dd('user store');
    }

    /**
     * Display the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show(User $users)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(User $users)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $users)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(User $user): RedirectResponse
    {
        $user->delete();

        return redirect()->back();
    }
}

app/Http/Livewire/Admin/Users/Create/Invitations.php
<?php

namespace App\Http\Livewire\Admin\Users\Create;

use App\Models\Invitation;
use Livewire\Component;

class Invitations extends Component
{
    public $invitations;

    public function render()
    {
        $this->invitations = Invitation::all();

        return view('livewire.admin.users.create.invitations');
    }

    public function delete($id)
    {
        Invitation::find($id)->delete();
    }
}

app/Http/Livewire/Admin/Users/Create/Invite.php
<?php

namespace App\Http\Livewire\Admin\Users\Create;

use App\Mail\UserInvitation;
use App\Models\Invitation;
use Exception;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Livewire\Component;

class Invite extends Component
{
    public $name;

    public $email;

    public $success;

    public $error;

    protected $rules = [
        'name' => 'required|string',
        'email' => 'required|email',
    ];

    public function render()
    {
        return view('livewire.admin.users.create.invite');
    }

    public function sendInvite()
    {
        $this->error = null;
        $this->success = null;
        $this->validate();

        try {
            $token = Str::random(50);

            Invitation::create([
                'name' => $this->name,
                'email' => $this->email,
                'token' => $token,
            ]);

            Mail::to($this->email)->send(new UserInvitation($token));
            $this->success = true;
            $this->name = null;
            $this->email = null;
        } catch (Exception $exception) {
            $this->error = __('Somehing went wrong. Check logs or try again later');
            Log::alert($exception->getMessage());
        }
    }
}

app/Http/Livewire/Admin/Users/Index/RoleSelect.php
<?php

namespace App\Http\Livewire\Admin\Users\Index;

use App\Models\User;
use Livewire\Component;
use Spatie\Permission\Models\Role;

class RoleSelect extends Component
{
    public $user;

    public $roles;

    public $userRole;

    public function mount(User $user)
    {
        $this->user = $user;
        $this->userRole = $user->getRoleNames()->first();
        $this->roles = Role::all();
    }

    public function render()
    {
        return view('livewire.admin.users.index.role-select');
    }

    public function select()
    {
        $this->user->assignRole($this->userRole);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/users/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Invite new user') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="overflow-hidden grid grid-cols-3">
                <div>
                    <h3 class="font-semibold text-lg text-gray-800 leading-tight">
                        {{ __('Invite new user') }}
                    </h3>
                    <p class="my-2 text-md text-gray-600">{{ __('Send email to worker with registration linke. Link expires after 24h') }}</p>
                </div>
                <div class="col-span-2">
                    <livewire:admin.users.create.invite></livewire:admin.users.create.invite>
                </div>

            </div>

            <livewire:admin.users.create.invitations></livewire:admin.users.create.invitations>
        </div>
    </div>
</x-app-layout>

resources/views/admin/users/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Users') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="overflow-hidden">
                @can('add users')
                    <div class="w-full text-right p-2">
                            <a href="{{ route('users.create') }}"><button
                                class="bg-gradient-base border border-blue-600 hover:bg-white text-white hover:text-blue-600 font-bold uppercase text-xs mt-5 py-2 px-4 rounded cursor-pointer">
                                {{ __('Invite new user') }}
                            </button>
                        </a>
                    </div>
                @endcan
                @can('edit users')
                    <div class="bg-white shadow-md rounded my-6">
                        <table class="min-w-max w-full table-auto">
                            <thead>
                                <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
                                    <th class="py-3 px-6 text-left">Name</th>
                                    <th class="py-3 px-6 text-left">Email</th>
                                    <th class="py-3 px-6 text-center">Role</th>
                                    <th class="py-3 px-6 text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody class="text-gray-600 text-sm font-light">
                                @foreach ($users as $user)
                                    <tr class="border-b border-gray-200 hover:bg-gray-100">
                                        <td class="py-3 px-6 text-left whitespace-nowrap">
                                            <div class="flex items-center">
                                                <span class="font-medium">{{ $user->name }}</span>
                                            </div>
                                        </td>
                                        <td class="py-3 px-6 text-left">
                                            <div class="flex items-center">
                                                <span>{{ $user->email }}</span>
                                            </div>
                                        </td>
                                        <td class="py-3 px-6 text-center">
                                            <livewire:admin.users.index.role-select :user="$user">
                                        </td>
                                        <td class="py-3 px-6 text-center">
                                            <div class="flex item-center justify-center">
                                                <form action="{{ route('users.destroy', [ 'user' => $user ]) }}" method="POST">
                                                    @csrf
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <button class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                                                            stroke="currentColor">
                                                            <path stroke-linecap="round" stroke-linejoin="round"
                                                                stroke-width="2"
                                                                d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                                        </svg>
                                                    </button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                @endcan
            </div>
        </div>
    </div>
</x-app-layout>